stages:
  - build
  - ckeck_style
  - test
  - deploy
  - notify

build_line:
  stage: build
  script:
    - cd src/grep
    - make s21_grep
    - make s21_cat
    - sh ../../ci-notify.sh ✅
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 day

ccplint_line:
  stage: ckeck_style
  script:
    - cd src/grep
    - make check_ccplint
    - sh ../../ci-notify.sh ✅
  allow_failure: false

test_line:
  stage: test
  needs: ["build_line", "ccplint_line"]
  script:
    - cd src/grep
    - make test
    - sh ../../ci-notify.sh ✅
  allow_failure: false

deploy_line:
  stage: deploy
  needs: ["test_line"]
  when: manual
  script:
    - cd src/grep
    - make s21_grep
    - make s21_cat
    - cd ../
    - chmod +x run_deploy.sh
    - ./run_deploy.sh
    - sh ../ci-notify.sh ✅
  allow_failure: false

notify_error:
  stage: notify
  script:
    - sh ./ci-notify.sh ❌
  when: on_failure
