stages:
  - build
  - ckeck_style
  - test
  - deploy

build_line:
  stage: build
  script:
    - cd src/grep
    - make
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 day

ccplint_line:
  stage: ckeck_style
  script:
    - cd src/grep
    - make check_ccplint
  allow_failure: false

test_line:
  stage: test
  needs: ["build_line", "ccplint_line"]
  script:
    - cd src/grep
    - make test
  allow_failure: false

deploy_line:
  stage: deploy
  needs: ["test_line"]
  when: manual
  script:
    - cd src/grep
    - make
    - cd ../
    - chmod +x run_deploy.sh
    - ./run_deploy.sh
  allow_failure: false

